/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esprit.egov.gui;


import esprit.egov.adapters.ActualitepostModel;
import esprit.egov.adapters.ButtonRender;
import esprit.egov.adapters.ButtondetailEditor;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTextField;


/**
 *
 * @author USER
 */
public class Actualitepost extends javax.swing.JFrame {

    /**
     * Creates new form Actualitepost
     */
//		DSFilterInfo[][] dsi = DSCapture.queryDevices();
//
//		DSFilterInfo info = dsi[0][0];
//
//	
//		final DSCapture capture = new DSCapture(0, info, true,
//				DSFilterInfo.doNotRender(),   null);
    Detailarticle da = new Detailarticle();

    public Actualitepost() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try{
            jTable1.setModel(new ActualitepostModel());
            jTable1.setRowHeight(70);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
            ButtonRender button = new ButtonRender();
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);

            jTable1.getColumn("details").setCellRenderer(button);

            jTable1.getColumn("details").setCellEditor(new ButtondetailEditor(new JTextField()));
        }

        catch (SQLException ex) {
            Logger.getLogger(Actualitepost.class.getName()).log(Level.SEVERE, null, ex);}
        catch (IOException ex) {
            Logger.getLogger(Actualitepost.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 550, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/Icon/backgroundpost.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        System.out.println(jTable1.getSelectedRow());
        String Textartcile = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);

        String Titreartcile = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1);
        Date datearticle = (Date) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2);
        ImageIcon ii = (ImageIcon) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3);
        ImageIcon i= new ImageIcon(ii.getImage().getScaledInstance(400,400, Image.SCALE_DEFAULT));
        da.setJLabel2(Titreartcile);
        da.setJLabel6(datearticle);
        da.setJLabel4(i);
        da.setJLabel5(Textartcile);
//        da.setJLabel4(Titreartcile);
        da.setVisible(true);
        da.pack();


    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//     DSEnvironment.unlockDLL("lundvall@telia.com", -513080L, 1833569L, 0L);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualitepost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
