/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esprit.egov.gui;

import esprit.egov.adapters.AppelOffreAdapter;
import esprit.egov.dao.classes.Appel_offreDao;
import esprit.egov.dao.interfaces.IAppel_offreDao;
import esprit.egov.entities.Appel_offre;
import java.util.Date;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author mouadh
 */
public class AppelOffre extends javax.swing.JFrame {

    /**
     * Creates new form Acceuil
     */
    public AppelOffre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jBtAddAppelOffre = new javax.swing.JButton();
        jBtUpdateAppelOffre = new javax.swing.JButton();
        jBtdeletAppelOffre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAppelOffre = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTftitre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTfobjet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDatChDeb = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jTflocalisation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTfprofil = new javax.swing.JTextField();
        jDatChfin = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextIDsearch = new javax.swing.JTextField();
        jButtonRecherche = new javax.swing.JButton();
        ConsulterCandidature = new javax.swing.JButton();
        AjouterCandidature = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        reponse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        jLabel2.setText("Appel d'Offre");

        jButton3.setText("home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jBtAddAppelOffre.setText("Ajouter Appel d'offre");
        jBtAddAppelOffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddAppelOffreActionPerformed(evt);
            }
        });

        jBtUpdateAppelOffre.setText("Modifier Appel d'offre");
        jBtUpdateAppelOffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtUpdateAppelOffreActionPerformed(evt);
            }
        });

        jBtdeletAppelOffre.setText("Supprimer Appel d'offre");
        jBtdeletAppelOffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtdeletAppelOffreActionPerformed(evt);
            }
        });

        jTableAppelOffre.setModel(new AppelOffreAdapter());
        jTableAppelOffre.setColumnSelectionAllowed(true);
        jTableAppelOffre.getTableHeader().setReorderingAllowed(false);
        jTableAppelOffre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAppelOffreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAppelOffre);
        jTableAppelOffre.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jLabel1.setText("Titre :");

        jTftitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTftitreActionPerformed(evt);
            }
        });

        jLabel3.setText("Objet : ");

        jLabel4.setText("Date début :");

        jLabel6.setText("Localisation :");

        jLabel7.setText("Profil demander :");

        jLabel5.setText("Date Fin :");

        jTextIDsearch.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextIDsearch.setToolTipText("search by id");

        jButtonRecherche.setText("Recherche");
        jButtonRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechercheActionPerformed(evt);
            }
        });

        ConsulterCandidature.setText("Consulter mes candidatures");
        ConsulterCandidature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterCandidatureActionPerformed(evt);
            }
        });

        AjouterCandidature.setText("Postuler Candidature");
        AjouterCandidature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterCandidatureActionPerformed(evt);
            }
        });

        jButton1.setText("return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTfobjet, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jTftitre)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDatChDeb, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTfprofil)
                            .addComponent(jTflocalisation)
                            .addComponent(jDatChfin, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addComponent(reponse))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(222, 222, 222)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtAddAppelOffre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtdeletAppelOffre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtUpdateAppelOffre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ConsulterCandidature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AjouterCandidature))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextIDsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRecherche)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtAddAppelOffre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtUpdateAppelOffre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtdeletAppelOffre))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTftitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTflocalisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reponse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTfobjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTfprofil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDatChDeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jDatChfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIDsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRecherche))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsulterCandidature)
                    .addComponent(AjouterCandidature)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Acceuil add = new Acceuil();
        add.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBtAddAppelOffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddAppelOffreActionPerformed
        if (jTfobjet.getText().isEmpty() || jTflocalisation.getText().isEmpty() || jTfprofil.getText().isEmpty()) {
            reponse.setText(" un champ obligatoire est vide");  
            }else
                        reponse.setText("");  

        try {
            Appel_offre appeloffre = new Appel_offre();
            appeloffre.setObjet(jTfobjet.getText());
            appeloffre.setDate_dep(jDatChDeb.getDate());
            appeloffre.setDate_fin(jDatChfin.getDate());
            appeloffre.setLocalisation(jTflocalisation.getText());
            appeloffre.setProfil_demander(jTfprofil.getText());
            IAppel_offreDao applOff = new Appel_offreDao();
            applOff.addAppel_offre(appeloffre);
            jTableAppelOffre.repaint();
            //jTableAppelOffre.refresh(appeloffre);
            JOptionPane.showMessageDialog(null, "enregistrer avec succée !");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
        jTableAppelOffre.repaint();

// TODO add your handling code here:
    }//GEN-LAST:event_jBtAddAppelOffreActionPerformed

    private void jTableAppelOffreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAppelOffreMouseClicked
        try {

            int row = jTableAppelOffre.getSelectedRow();
            String idAppelOffre = jTableAppelOffre.getValueAt(row, 0).toString();
            jTfobjet.setText(jTableAppelOffre.getValueAt(row, 1).toString());
            jDatChDeb.setDate((Date) jTableAppelOffre.getValueAt(row, 3));
            jDatChfin.setDate((Date) jTableAppelOffre.getValueAt(row, 4));
            jTflocalisation.setText(jTableAppelOffre.getValueAt(row, 5).toString());
            jTfprofil.setText(jTableAppelOffre.getValueAt(row, 6).toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableAppelOffreMouseClicked

    private void jTftitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTftitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTftitreActionPerformed

    private void jBtUpdateAppelOffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtUpdateAppelOffreActionPerformed
try {
            int row = jTableAppelOffre.getSelectedRow();
            Object idAppelOffre = jTableAppelOffre.getValueAt(row, 0);
            Appel_offre appeloffre = new Appel_offre();
            appeloffre.setObjet(jTfobjet.getText());
            appeloffre.setDate_dep(jDatChDeb.getDate());
            appeloffre.setDate_fin(jDatChfin.getDate());
            appeloffre.setLocalisation(jTflocalisation.getText());
            appeloffre.setProfil_demander(jTfprofil.getText());
            appeloffre.setId_appel(Integer.valueOf(idAppelOffre.toString()));
            IAppel_offreDao applOff = new Appel_offreDao();
            applOff.updateAppel_offre(appeloffre);
            //jTableAppelOffre.refresh(appeloffre);
            JOptionPane.showMessageDialog(null, "modification avec succée !");
                        jTableAppelOffre.setModel(new AppelOffreAdapter());

jScrollPane1.setViewportView(jTableAppelOffre);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jBtUpdateAppelOffreActionPerformed

    private void jBtdeletAppelOffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtdeletAppelOffreActionPerformed
try {
            int row = jTableAppelOffre.getSelectedRow();
            Object idAppelOffre = jTableAppelOffre.getValueAt(row, 0);
            Appel_offre appeloffre = new Appel_offre();
                        appeloffre.setId_appel(Integer.valueOf(idAppelOffre.toString()));
            IAppel_offreDao applOff = new Appel_offreDao();
            applOff.removeAppel_offreById(appeloffre);
            //jTableAppelOffre.refresh(appeloffre);
            JOptionPane.showMessageDialog(null, "supression avec succée !");
            jTableAppelOffre.setModel(new AppelOffreAdapter());
jScrollPane1.setViewportView(jTableAppelOffre);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jBtdeletAppelOffreActionPerformed

    private void jButtonRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechercheActionPerformed
//         IAppel_offreDao appel_offreDao = new Appel_offreDao();
//            if (jTextIDsearch.equals("")) {
//            JOptionPane.showMessageDialog(null,
//                    "SVP enter l'id de l'appel d'offre a chercheé");
//        }
//             String s=appel_offreDao.findAppel_offreById();
//       if(!(jTextIDsearch.getText().equals(s))){
//                 JOptionPane.showMessageDialog(this, "Ce id n'existe pas");
//
//       }
//            else {
//                
//            AppelOffre appelOffre = new AppelOffre();
//           appelOffre= appel_offreDao.findAppel_offreById(jTextIDsearch.get());
//       }
            }//GEN-LAST:event_jButtonRechercheActionPerformed

    private void ConsulterCandidatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterCandidatureActionPerformed
 ConsulterCandidature add = new ConsulterCandidature();
        add.setVisible(true);
        this.setVisible(false);         }//GEN-LAST:event_ConsulterCandidatureActionPerformed

    private void AjouterCandidatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterCandidatureActionPerformed
               int row = jTableAppelOffre.getSelectedRow();
            Object idAppelOffre = jTableAppelOffre.getValueAt(row, 0);
        AjoutCandidature add = new AjoutCandidature((Integer) idAppelOffre);
        
        add.setVisible(true);
        this.setVisible(false);         }//GEN-LAST:event_AjouterCandidatureActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Ejob add = new Ejob();
add.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppelOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppelOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppelOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppelOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppelOffre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterCandidature;
    private javax.swing.JButton ConsulterCandidature;
    private javax.swing.JButton jBtAddAppelOffre;
    private javax.swing.JButton jBtUpdateAppelOffre;
    private javax.swing.JButton jBtdeletAppelOffre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonRecherche;
    private com.toedter.calendar.JDateChooser jDatChDeb;
    private com.toedter.calendar.JDateChooser jDatChfin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAppelOffre;
    private javax.swing.JTextField jTextIDsearch;
    private javax.swing.JTextField jTflocalisation;
    private javax.swing.JTextField jTfobjet;
    private javax.swing.JTextField jTfprofil;
    private javax.swing.JTextField jTftitre;
    private javax.swing.JLabel reponse;
    // End of variables declaration//GEN-END:variables
}
