/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esprit.egov.gui;

import esprit.egov.dao.classes.ActesJuridiquesDao;
import esprit.egov.dao.classes.UtilisateurDao;
import esprit.egov.dao.interfaces.IActesJuridiquesDao;
import esprit.egov.dao.interfaces.IUtilisateurDao;
import esprit.egov.entities.Utilisateur;
import java.awt.Image;
import java.text.MessageFormat;
import java.util.List;
import java.awt.PrintGraphics.*;
import java.sql.Blob;
import java.text.*;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbookpro
 */
public class ListeCitoyens_admin extends javax.swing.JFrame {

    void updateTable() {
        DefaultTableModel model = (DefaultTableModel) DemandesCin.getModel();
        model.setRowCount(0);
        IUtilisateurDao utiDao = new UtilisateurDao();
        List<Utilisateur> listeCin = utiDao.findAllCin();
        for (Utilisateur ind : listeCin) {
            model.addRow(
                    new Object[]{ind.getIduti(),ind.getNumCin() ,ind.getNom(), ind.getPrenom(), ind.getDateNaissance()
                               , ind.getLieuNaissance(), ind.getNomPere(), ind.getPrenomPere()
                               , ind.getNomMere(), ind.getPrenomMere(), ind.getSexe()
                               , ind.getStatutSocial(), ind.getAdresse(), ind.getProfession()
                    }
            );
        }
    }

    public ListeCitoyens_admin() {
        initComponents();
        updateTable();
    }
    public ListeCitoyens_admin(int idActeJuri) {
        initComponents();
        updateTable();
        IdActeJuridique=idActeJuri;
        NumActe.setText("Numéro acte: "+idActeJuri);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        PrenomMère = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Back = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DemandesCin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Prenom = new javax.swing.JTextField();
        DateNaiss = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LieuNaiss = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Masculin = new javax.swing.JRadioButton();
        Feminin = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        NomPére = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PrenomPére = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NomMère = new javax.swing.JTextField();
        PrenomMère1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Condamner = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Adresse = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Profession = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        statutsocial = new javax.swing.JTextField();
        photoLabel = new javax.swing.JLabel();
        NumCin = new javax.swing.JLabel();
        NumActe = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ListeDemandesEN = new javax.swing.JMenuItem();
        ListeEN = new javax.swing.JMenuItem();
        StatEN = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ListeDemandesCin = new javax.swing.JMenuItem();
        ListeCin = new javax.swing.JMenuItem();
        StatCin = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ActesJuri = new javax.swing.JMenuItem();
        ListeDemandesB3 = new javax.swing.JMenuItem();
        ListeB3 = new javax.swing.JMenuItem();
        StatB3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        PrenomMère.setText("Nom Mère");
        PrenomMère.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomMèreActionPerformed(evt);
            }
        });

        jLabel8.setText("Prénom mère:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/back.png")); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Home.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/home.png")); // NOI18N
        Home.setText("Home");
        Home.setSize(new java.awt.Dimension(40, 20));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setText("E-gov");

        DemandesCin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Num Cin", "Nom", "Prenom", "Date de naissance", "Lieu de naissance", "Nom Pere", "Prenom Pere", "Nom mere", "Prenom Mere", "Sexe", "Statut social", "Adresse", "Profession"
            }
        ));
        DemandesCin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DemandesCinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DemandesCin);

        jLabel2.setText("Nom:");

        Nom.setText("Nom");
        Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomActionPerformed(evt);
            }
        });

        jLabel3.setText("Prénom:");

        Prenom.setText("Prenom");
        Prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomActionPerformed(evt);
            }
        });

        jLabel4.setText("Date de naissance:");

        jLabel10.setText("Lieu de naissance:");

        LieuNaiss.setText("Lieu naissance");
        LieuNaiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LieuNaissActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexe:");

        buttonGroup1.add(Masculin);
        Masculin.setText("Masculin");
        Masculin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasculinActionPerformed(evt);
            }
        });

        buttonGroup1.add(Feminin);
        Feminin.setText("Feminin");
        Feminin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemininActionPerformed(evt);
            }
        });

        jLabel6.setText("Nom pére:");

        NomPére.setText("Nom Pére");
        NomPére.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomPéreActionPerformed(evt);
            }
        });

        jLabel7.setText("Prénom pére:");

        PrenomPére.setText("Prénom Pére");
        PrenomPére.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomPéreActionPerformed(evt);
            }
        });

        jLabel9.setText("Nom mère:");

        NomMère.setText("Nom Mère");
        NomMère.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomMèreActionPerformed(evt);
            }
        });

        PrenomMère1.setText("Nom Mère");
        PrenomMère1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomMère1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Prénom mère:");

        Condamner.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/ok.png")); // NOI18N
        Condamner.setText("Condamner");
        Condamner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CondamnerActionPerformed(evt);
            }
        });

        jLabel12.setText("Adresse:");

        jLabel13.setText("Profession:");

        jLabel14.setText("Statut social");

        statutsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statutsocialActionPerformed(evt);
            }
        });

        photoLabel.setText("photo");

        NumCin.setText("Cin numéro:");

        NumActe.setText("Acte numéro:");

        jMenu1.setText("Extraits de naissances");

        ListeDemandesEN.setText("Liste demandes");
        ListeDemandesEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeDemandesENActionPerformed(evt);
            }
        });
        jMenu1.add(ListeDemandesEN);

        ListeEN.setText("Liste extraits");
        ListeEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeENActionPerformed(evt);
            }
        });
        jMenu1.add(ListeEN);

        StatEN.setText("Statistiques");
        jMenu1.add(StatEN);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cartes d'identité nationale");

        ListeDemandesCin.setText("Liste Demandes");
        ListeDemandesCin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeDemandesCinActionPerformed(evt);
            }
        });
        jMenu2.add(ListeDemandesCin);

        ListeCin.setText("Liste CIN");
        ListeCin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeCinActionPerformed(evt);
            }
        });
        jMenu2.add(ListeCin);

        StatCin.setText("Statistiques");
        jMenu2.add(StatCin);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Bulletins numéro 3");

        ActesJuri.setText("Actes juridiques");
        ActesJuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActesJuriActionPerformed(evt);
            }
        });
        jMenu3.add(ActesJuri);

        ListeDemandesB3.setText("Liste demandes");
        ListeDemandesB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeDemandesB3ActionPerformed(evt);
            }
        });
        jMenu3.add(ListeDemandesB3);

        ListeB3.setText("Liste B3");
        jMenu3.add(ListeB3);

        StatB3.setText("Statistiques");
        jMenu3.add(StatB3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(NomPére, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Masculin)
                                            .addGap(18, 18, 18)
                                            .addComponent(Feminin))
                                        .addComponent(LieuNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(PrenomPére, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NomMère)
                                    .addGap(32, 32, 32))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PrenomMère1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(NumActe, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(NumCin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(113, 113, 113)
                                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statutsocial, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Profession, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(Condamner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Home)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NumActe, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NumCin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(DateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LieuNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Masculin)
                            .addComponent(Feminin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(NomPére, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(PrenomPére, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(NomMère, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrenomMère1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Profession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statutsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(Home)
                    .addComponent(Condamner))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Acceuil_admin add = new Acceuil_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
       login add = new login();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void ListeDemandesENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeDemandesENActionPerformed
        ListeCitoyens_admin add = new ListeCitoyens_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeDemandesENActionPerformed

    private void ListeDemandesCinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeDemandesCinActionPerformed
        ListeCitoyens_admin add = new ListeCitoyens_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeDemandesCinActionPerformed

    private void ListeDemandesB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeDemandesB3ActionPerformed
        ListeCondamnes_admin add = new ListeCondamnes_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeDemandesB3ActionPerformed

    private void NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomActionPerformed

    private void PrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomActionPerformed

    private void LieuNaissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LieuNaissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LieuNaissActionPerformed

    private void MasculinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasculinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasculinActionPerformed

    private void FemininActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemininActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemininActionPerformed

    private void NomPéreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomPéreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomPéreActionPerformed

    private void PrenomPéreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomPéreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomPéreActionPerformed

    private void NomMèreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomMèreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomMèreActionPerformed

    private void PrenomMèreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomMèreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomMèreActionPerformed

    private void PrenomMère1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomMère1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomMère1ActionPerformed

    private void DemandesCinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DemandesCinMouseClicked
        int row = DemandesCin.getSelectedRow();
        NumCin.setText(DemandesCin.getModel().getValueAt(row, 1).toString());
        String nom = (DemandesCin.getModel().getValueAt(row, 2).toString());
        Nom.setText(nom);
        String pnom = (DemandesCin.getModel().getValueAt(row, 3).toString());
        Prenom.setText(pnom);
        Date dateNaiss = (Date) DemandesCin.getModel().getValueAt(row, 4);
        DateNaiss.setDate(dateNaiss);
        String Lieu = (DemandesCin.getModel().getValueAt(row, 5).toString());
        LieuNaiss.setText(Lieu);
        String nomP = (DemandesCin.getModel().getValueAt(row, 6).toString());
        NomPére.setText(nomP);
        String pnomP = (DemandesCin.getModel().getValueAt(row, 7).toString());
        PrenomPére.setText(pnomP);
        String nomM = (DemandesCin.getModel().getValueAt(row, 8).toString());
        NomMère.setText(nomM);
        String pnomM = (DemandesCin.getModel().getValueAt(row, 9).toString());
        PrenomMère1.setText(pnomM);
        String sexe = (DemandesCin.getModel().getValueAt(row, 10).toString());
        if (sexe.equalsIgnoreCase("Feminin") || sexe.equalsIgnoreCase("Feminin")) {
            Feminin.setSelected(true);
        }
        if (sexe.equalsIgnoreCase("Masculin") || sexe.equalsIgnoreCase("masculin")) {
            Masculin.setSelected(true);
        }
        String statutSocial = DemandesCin.getModel().getValueAt(row, 11).toString();
        statutsocial.setText(statutSocial);
        String adr = DemandesCin.getModel().getValueAt(row, 12).toString();
        Adresse.setText(adr);
        String prof = DemandesCin.getModel().getValueAt(row, 13).toString();
        Profession.setText(prof);
        IUtilisateurDao utiDao = new UtilisateurDao();
        Image imageUti = utiDao.findUtiPhotoByid((int) DemandesCin.getModel().getValueAt(row, 0));
        Image im = imageUti.getScaledInstance(photoLabel.getWidth(), photoLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(im);
        photoLabel.setIcon(newImage);
    }//GEN-LAST:event_DemandesCinMouseClicked

    private void CondamnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CondamnerActionPerformed

        int row = DemandesCin.getSelectedRow();
        String NumCin= DemandesCin.getModel().getValueAt(row, 1).toString();
        IUtilisateurDao utiDao = new UtilisateurDao();
        System.out.println("Acte: "+IdActeJuridique+"  Cit: "+NumCin);
         IActesJuridiquesDao acteDao = new  ActesJuridiquesDao();
         acteDao.CondamnerUti(IdActeJuridique,NumCin);
    }//GEN-LAST:event_CondamnerActionPerformed

    private void ListeENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeENActionPerformed
        RechercheEN_admin add = new RechercheEN_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeENActionPerformed

    private void statutsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statutsocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statutsocialActionPerformed

    private void ListeCinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeCinActionPerformed
        RechercheCin_admin add = new RechercheCin_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeCinActionPerformed

    private void ActesJuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActesJuriActionPerformed
        ListeActesJuridiques_admin listeAJ = new ListeActesJuridiques_admin();
        listeAJ.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ActesJuriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeCitoyens_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeCitoyens_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeCitoyens_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeCitoyens_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeCitoyens_admin().setVisible(true);
            }
        });
    }
int IdActeJuridique;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActesJuri;
    private javax.swing.JTextField Adresse;
    private javax.swing.JButton Back;
    private javax.swing.JButton Condamner;
    private com.toedter.calendar.JDateChooser DateNaiss;
    private javax.swing.JTable DemandesCin;
    private javax.swing.JRadioButton Feminin;
    private javax.swing.JButton Home;
    private javax.swing.JTextField LieuNaiss;
    private javax.swing.JMenuItem ListeB3;
    private javax.swing.JMenuItem ListeCin;
    private javax.swing.JMenuItem ListeDemandesB3;
    private javax.swing.JMenuItem ListeDemandesCin;
    private javax.swing.JMenuItem ListeDemandesEN;
    private javax.swing.JMenuItem ListeEN;
    private javax.swing.JRadioButton Masculin;
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField NomMère;
    private javax.swing.JTextField NomPére;
    private javax.swing.JLabel NumActe;
    private javax.swing.JLabel NumCin;
    private javax.swing.JTextField Prenom;
    private javax.swing.JTextField PrenomMère;
    private javax.swing.JTextField PrenomMère1;
    private javax.swing.JTextField PrenomPére;
    private javax.swing.JTextField Profession;
    private javax.swing.JMenuItem StatB3;
    private javax.swing.JMenuItem StatCin;
    private javax.swing.JMenuItem StatEN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField statutsocial;
    // End of variables declaration//GEN-END:variables
}
