/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esprit.egov.gui;

import esprit.egov.dao.classes.UtilisateurDao;
import esprit.egov.dao.interfaces.IUtilisateurDao;
import esprit.egov.entities.Utilisateur;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.PrintGraphics.*;
import java.text.*;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbookpro
 */
public class RechercheCin_admin extends javax.swing.JFrame {

    /**
     * Creates new form AddEN
     */
    public RechercheCin_admin() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) DemandesCin.getModel();
        model.setRowCount(0);
        IUtilisateurDao utiDao = new UtilisateurDao();
        List<Utilisateur> listeCin = utiDao.findAllCin();
        for (Utilisateur ind : listeCin) {
            model.addRow(
                    new Object[]{ind.getIduti(), ind.getNom(), ind.getPrenom(), ind.getDateNaissance(), ind.getLieuNaissance()
                            , ind.getNomPere(), ind.getPrenomPere(), ind.getNomMere(), ind.getPrenomMere(), ind.getSexe()
                            ,ind.getStatutSocial(),ind.getAdresse(),ind.getProfession(),ind.getDateDelivrenceCin()
                    }
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Back = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DemandesCin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        CinRech = new javax.swing.JTextField();
        Trouver = new javax.swing.JButton();
        Imprimer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ListeDemandesEN = new javax.swing.JMenuItem();
        ListeEN = new javax.swing.JMenuItem();
        StatEN = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ListeDemandesCin = new javax.swing.JMenuItem();
        ListeCin = new javax.swing.JMenuItem();
        StatCin = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ActesJuri = new javax.swing.JMenuItem();
        ListeDemandesB3 = new javax.swing.JMenuItem();
        ListeB3 = new javax.swing.JMenuItem();
        StatB3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/back.png")); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Home.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/home.png")); // NOI18N
        Home.setText("Home");
        Home.setSize(new java.awt.Dimension(40, 20));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setText("E-gov");

        DemandesCin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prenom", "Date de naissance", "Lieu de naissance", "Nom Pere", "Prenom Pere", "Nom mere", "Prenom Mere", "Sexe", "Statut social", "Adresse", "Profession", "Date délivrencel"
            }
        ));
        jScrollPane1.setViewportView(DemandesCin);

        jLabel2.setText("numéro CIN:");

        CinRech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CinRechKeyReleased(evt);
            }
        });

        Trouver.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/find.png")); // NOI18N
        Trouver.setText("Trouver");
        Trouver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrouverActionPerformed(evt);
            }
        });

        Imprimer.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/print.png")); // NOI18N
        Imprimer.setText("Imprimer");
        Imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimerActionPerformed(evt);
            }
        });

        jMenu1.setText("Extraits de naissances");

        ListeDemandesEN.setText("Liste demandes");
        ListeDemandesEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeDemandesENActionPerformed(evt);
            }
        });
        jMenu1.add(ListeDemandesEN);

        ListeEN.setText("Liste extraits");
        ListeEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeENActionPerformed(evt);
            }
        });
        jMenu1.add(ListeEN);

        StatEN.setText("Statistiques");
        jMenu1.add(StatEN);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cartes d'identité nationale");

        ListeDemandesCin.setText("Liste Demandes");
        ListeDemandesCin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeDemandesCinActionPerformed(evt);
            }
        });
        jMenu2.add(ListeDemandesCin);

        ListeCin.setText("Liste CIN");
        ListeCin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeCinActionPerformed(evt);
            }
        });
        jMenu2.add(ListeCin);

        StatCin.setText("Statistiques");
        jMenu2.add(StatCin);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Bulletins numéro 3");

        ActesJuri.setText("Actes juridiques");
        ActesJuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActesJuriActionPerformed(evt);
            }
        });
        jMenu3.add(ActesJuri);

        ListeDemandesB3.setText("Liste demandes");
        ListeDemandesB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeDemandesB3ActionPerformed(evt);
            }
        });
        jMenu3.add(ListeDemandesB3);

        ListeB3.setText("Liste B3");
        jMenu3.add(ListeB3);

        StatB3.setText("Statistiques");
        jMenu3.add(StatB3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CinRech, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(Trouver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CinRech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Trouver)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back)
                    .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Acceuil_admin add = new Acceuil_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        login add = new login();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void ListeDemandesENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeDemandesENActionPerformed
        ListeDemandesEN_admin add = new ListeDemandesEN_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeDemandesENActionPerformed

    private void ListeDemandesCinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeDemandesCinActionPerformed
        ListeDemandesCin_admin add = new ListeDemandesCin_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeDemandesCinActionPerformed

    private void ListeDemandesB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeDemandesB3ActionPerformed
        ListeCondamnes_admin add = new ListeCondamnes_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeDemandesB3ActionPerformed

    private void TrouverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrouverActionPerformed

        IUtilisateurDao utiDao = new UtilisateurDao();
        List<Utilisateur> listeCIN = utiDao.findUtilisateurByCIN(CinRech.getText());
        DefaultTableModel model = (DefaultTableModel) DemandesCin.getModel();
        model.setRowCount(0);
        for (Utilisateur ind : listeCIN) {
            model.addRow(
                    new Object[]{ind.getIduti(), ind.getNom(), ind.getPrenom(), ind.getDateNaissance(), ind.getLieuNaissance()
                            , ind.getNomPere(), ind.getPrenomPere(), ind.getNomMere(), ind.getPrenomMere(), ind.getSexe()
                            ,ind.getStatutSocial(),ind.getAdresse(),ind.getProfession(),ind.getDateDelivrenceCin()
                    }
            );
        }
    }//GEN-LAST:event_TrouverActionPerformed

    private void CinRechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CinRechKeyReleased


    }//GEN-LAST:event_CinRechKeyReleased

    private void ImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimerActionPerformed
        MessageFormat header = new MessageFormat("Liste des CIN \n Nom: " + CinRech.getText() + "\n\n");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            DemandesCin.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erreur lors de l'impression ", e.getMessage());
        }
    }//GEN-LAST:event_ImprimerActionPerformed

    private void ListeENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeENActionPerformed
        RechercheEN_admin add = new RechercheEN_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeENActionPerformed

    private void ListeCinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeCinActionPerformed
        RechercheCin_admin add = new RechercheCin_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeCinActionPerformed

    private void ActesJuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActesJuriActionPerformed
       ListeActesJuridiques_admin listeAJ = new ListeActesJuridiques_admin();
       listeAJ.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_ActesJuriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercheCin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercheCin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercheCin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercheCin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RechercheCin_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActesJuri;
    private javax.swing.JButton Back;
    private javax.swing.JTextField CinRech;
    private javax.swing.JTable DemandesCin;
    private javax.swing.JButton Home;
    private javax.swing.JButton Imprimer;
    private javax.swing.JMenuItem ListeB3;
    private javax.swing.JMenuItem ListeCin;
    private javax.swing.JMenuItem ListeDemandesB3;
    private javax.swing.JMenuItem ListeDemandesCin;
    private javax.swing.JMenuItem ListeDemandesEN;
    private javax.swing.JMenuItem ListeEN;
    private javax.swing.JMenuItem StatB3;
    private javax.swing.JMenuItem StatCin;
    private javax.swing.JMenuItem StatEN;
    private javax.swing.JButton Trouver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
