/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esprit.egov.gui;

import esprit.egov.dao.classes.UtilisateurDao;
import esprit.egov.dao.interfaces.IUtilisateurDao;
import esprit.egov.entities.Utilisateur;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.PrintGraphics.*;
import java.text.*;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbookpro
 */
public class RechercheEN_admin extends javax.swing.JFrame {

    /**
     * Creates new form AddEN
     */
    void updateTable() {
        DefaultTableModel model = (DefaultTableModel) DemandesEN.getModel();
        IUtilisateurDao utiDao = new UtilisateurDao();
        model.setRowCount(0);
        List<Utilisateur> listeEN = utiDao.findAllEN();
        for (Utilisateur ind : listeEN) {
            model.addRow(
                    new Object[]{ind.getIduti(), ind.getNom(), ind.getPrenom(), ind.getDateNaissance(), ind.getLieuNaissance(), ind.getNomPere(), ind.getPrenomPere(), ind.getNomMere(), ind.getPrenomMere(), ind.getSexe()
                    }
            );
        }
    }

    void updateTable(String nom) {
        DefaultTableModel model = (DefaultTableModel) DemandesEN.getModel();
        IUtilisateurDao utiDao = new UtilisateurDao();
        model.setRowCount(0);
        List<Utilisateur> listeExtNaiss = utiDao.findUtilisateurByNom(nom);
        listeExtNaiss.stream().forEach((ind) -> {
            model.addRow(
                    new Object[]{ind.getIduti(), ind.getNom(), ind.getPrenom(), ind.getDateNaissance(), ind.getLieuNaissance(), ind.getNomPere(), ind.getPrenomPere(), ind.getNomMere(), ind.getPrenomMere(), ind.getSexe()
                    }
            );
        });
    }

    void updateTable(String nom, String prenom, Date dateNaiss) {
        IUtilisateurDao utiDao = new UtilisateurDao();
        List<Utilisateur> listeEN = utiDao.findUtilisateurByNomPrenomDateNaiss(nom, prenom, dateNaiss);

        DefaultTableModel model = (DefaultTableModel) DemandesEN.getModel();
        for (Utilisateur ind : listeEN) {
            model.addRow(
                    new Object[]{ind.getNom(), ind.getPrenom(), ind.getDateNaissance(), ind.getLieuNaissance(), ind.getNomPere(), ind.getPrenomPere(), ind.getNomMere(), ind.getPrenomMere(), ind.getSexe()
                    }
            );
        }

    }

    public RechercheEN_admin() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) DemandesEN.getModel();
        model.setRowCount(0);
        IUtilisateurDao utiDao = new UtilisateurDao();
        List<Utilisateur> listeE = utiDao.findAllEN();
        for (Utilisateur ind : listeE) {
            model.addRow(
                    new Object[]{ind.getIduti(), ind.getNom(), ind.getPrenom(), ind.getDateNaissance(), ind.getLieuNaissance(), ind.getNomPere(), ind.getPrenomPere(), ind.getNomMere(), ind.getPrenomMere(), ind.getSexe()
                    }
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Back = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DemandesEN = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Pnom = new javax.swing.JTextField();
        NomRech = new javax.swing.JTextField();
        DateNaiss = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Trouver = new javax.swing.JButton();
        Imprimer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ListeDemandesEN = new javax.swing.JMenuItem();
        ListeEN = new javax.swing.JMenuItem();
        StatEN = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ListeDemandesCin = new javax.swing.JMenuItem();
        ListeCin = new javax.swing.JMenuItem();
        StatCin = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ActesJuri = new javax.swing.JMenuItem();
        ListeDemandesB3 = new javax.swing.JMenuItem();
        ListeB3 = new javax.swing.JMenuItem();
        StatB3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/back.png")); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Home.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/home.png")); // NOI18N
        Home.setText("Home");
        Home.setSize(new java.awt.Dimension(40, 20));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setText("E-gov");

        DemandesEN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prenom", "Date de naissance", "Lieu de naissance", "Nom Pere", "Prenom Pere", "Nom mere", "Prenom Mere", "Sexe"
            }
        ));
        jScrollPane1.setViewportView(DemandesEN);

        jLabel2.setText("Nom");

        Pnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnomActionPerformed(evt);
            }
        });

        NomRech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NomRechKeyReleased(evt);
            }
        });

        jLabel3.setText("Prénom");

        jLabel4.setText("Date de naissance");

        Trouver.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/find.png")); // NOI18N
        Trouver.setText("Trouver");
        Trouver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrouverActionPerformed(evt);
            }
        });

        Imprimer.setIcon(new javax.swing.ImageIcon("/Users/macbookpro/Desktop/3A13/PiDev/JavaSprint/Pi_Egov/images/print.png")); // NOI18N
        Imprimer.setText("Imprimer");
        Imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimerActionPerformed(evt);
            }
        });

        jMenu1.setText("Extraits de naissances");

        ListeDemandesEN.setText("Liste demandes");
        ListeDemandesEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeDemandesENActionPerformed(evt);
            }
        });
        jMenu1.add(ListeDemandesEN);

        ListeEN.setText("Liste extraits");
        ListeEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeENActionPerformed(evt);
            }
        });
        jMenu1.add(ListeEN);

        StatEN.setText("Statistiques");
        StatEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatENActionPerformed(evt);
            }
        });
        jMenu1.add(StatEN);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cartes d'identité nationale");

        ListeDemandesCin.setText("Liste Demandes");
        ListeDemandesCin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeDemandesCinActionPerformed(evt);
            }
        });
        jMenu2.add(ListeDemandesCin);

        ListeCin.setText("Liste CIN");
        jMenu2.add(ListeCin);

        StatCin.setText("Statistiques");
        jMenu2.add(StatCin);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Bulletins numéro 3");

        ActesJuri.setText("Actes juridiques");
        ActesJuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActesJuriActionPerformed(evt);
            }
        });
        jMenu3.add(ActesJuri);

        ListeDemandesB3.setText("Liste demandes");
        ListeDemandesB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeDemandesB3ActionPerformed(evt);
            }
        });
        jMenu3.add(ListeDemandesB3);

        ListeB3.setText("Liste B3");
        jMenu3.add(ListeB3);

        StatB3.setText("Statistiques");
        jMenu3.add(StatB3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(NomRech, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(21, 21, 21)
                .addComponent(Pnom, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(DateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Trouver)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(Pnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NomRech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Trouver)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Home)
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Acceuil_admin add = new Acceuil_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        login add = new login();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void ListeDemandesENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeDemandesENActionPerformed
        ListeDemandesEN_admin add = new ListeDemandesEN_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeDemandesENActionPerformed

    private void ListeDemandesCinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeDemandesCinActionPerformed
        ListeDemandesCin_admin add = new ListeDemandesCin_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeDemandesCinActionPerformed

    private void ListeDemandesB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeDemandesB3ActionPerformed
        ListeCondamnes_admin add = new ListeCondamnes_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeDemandesB3ActionPerformed

    private void PnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnomActionPerformed

    private void TrouverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrouverActionPerformed
        String nom = NomRech.getText();
        String pnom = Pnom.getText();
        Date dateNaiss = DateNaiss.getDate();
        updateTable(nom, pnom, dateNaiss);

    }//GEN-LAST:event_TrouverActionPerformed

    private void NomRechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomRechKeyReleased

        String nom = NomRech.getText();
        if (nom.isEmpty()) {
            updateTable();
        }
        if (!nom.isEmpty()) {
            updateTable(nom);
        }

    }//GEN-LAST:event_NomRechKeyReleased

    private void ImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimerActionPerformed
        MessageFormat header = new MessageFormat("Liste d'extraits de naissance \n Nom: " + NomRech.getText() + "\n Prénom: " + Pnom + "\n Date de naissance:\n" + DateNaiss.getDateFormatString() + "\n\n");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            DemandesEN.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erreur lors de l'impression ", e.getMessage());
        }
    }//GEN-LAST:event_ImprimerActionPerformed

    private void ListeENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeENActionPerformed
        RechercheEN_admin add = new RechercheEN_admin();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListeENActionPerformed

    private void ActesJuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActesJuriActionPerformed
        ListeActesJuridiques_admin listeAJ = new ListeActesJuridiques_admin();
        listeAJ.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ActesJuriActionPerformed

    private void StatENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatENActionPerformed
        this.setVisible(false);
        chartSexe ch = new chartSexe();
        ch.setVisible(true);
    }//GEN-LAST:event_StatENActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercheEN_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercheEN_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercheEN_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercheEN_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RechercheEN_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActesJuri;
    private javax.swing.JButton Back;
    private com.toedter.calendar.JDateChooser DateNaiss;
    private javax.swing.JTable DemandesEN;
    private javax.swing.JButton Home;
    private javax.swing.JButton Imprimer;
    private javax.swing.JMenuItem ListeB3;
    private javax.swing.JMenuItem ListeCin;
    private javax.swing.JMenuItem ListeDemandesB3;
    private javax.swing.JMenuItem ListeDemandesCin;
    private javax.swing.JMenuItem ListeDemandesEN;
    private javax.swing.JMenuItem ListeEN;
    private javax.swing.JTextField NomRech;
    private javax.swing.JTextField Pnom;
    private javax.swing.JMenuItem StatB3;
    private javax.swing.JMenuItem StatCin;
    private javax.swing.JMenuItem StatEN;
    private javax.swing.JButton Trouver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
