/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esprit.egov.gui;

import esprit.egov.dao.classes.PasseportDao;
import esprit.egov.dao.classes.PermisDao;
import esprit.egov.entities.Passeport;
import esprit.egov.entities.Permis;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

/**
 *
 * @author boumaiza
 */
public class showPasseport extends javax.swing.JFrame {

    /**
     * Creates new form showPasseport
     */
    public showPasseport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EN = new javax.swing.JPanel();
        j = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        categorie_permis = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Date_validite_permis = new javax.swing.JLabel();
        NumCin = new javax.swing.JLabel();
        date_creation_permis = new javax.swing.JLabel();
        numPermis1 = new javax.swing.JLabel();
        pass = new javax.swing.JPanel();
        j1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        couleur = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateValidite = new javax.swing.JLabel();
        NumCin1 = new javax.swing.JLabel();
        dateDeliv = new javax.swing.JLabel();
        numPass = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        numPasseport = new javax.swing.JTextField();
        Trouver = new javax.swing.JButton();
        Imprimer = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        Statistique = new javax.swing.JButton();

        j.setText("date_creation_permis");

        jLabel3.setText("categorie_permis:");

        categorie_permis.setText("categorie_permis..");

        jLabel4.setText("Date_validite_permis:");

        Date_validite_permis.setText("Date_validite_permis..");

        NumCin.setText("numPermis...");

        date_creation_permis.setText("date_creation_permis...");

        numPermis1.setText("numPermis..");

        javax.swing.GroupLayout ENLayout = new javax.swing.GroupLayout(EN);
        EN.setLayout(ENLayout);
        ENLayout.setHorizontalGroup(
            ENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ENLayout.createSequentialGroup()
                .addGroup(ENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ENLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Date_validite_permis, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ENLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(NumCin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ENLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(ENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ENLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(categorie_permis, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ENLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(ENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numPermis1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date_creation_permis, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        ENLayout.setVerticalGroup(
            ENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ENLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numPermis1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(ENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_creation_permis))
                .addGap(47, 47, 47)
                .addGroup(ENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(categorie_permis))
                .addGap(65, 65, 65)
                .addGroup(ENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Date_validite_permis))
                .addGap(135, 135, 135))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j1.setText("dateDelivrance");

        jLabel5.setText("couleurYeux");

        couleur.setText("couleurYeux..");

        jLabel6.setText("Date_validite_permis:");

        dateValidite.setText("Date_validite_permis..");

        NumCin1.setText("numPasseport...");

        dateDeliv.setText("dateDelivrance...");

        numPass.setText("numPasseport..");

        javax.swing.GroupLayout passLayout = new javax.swing.GroupLayout(pass);
        pass.setLayout(passLayout);
        passLayout.setHorizontalGroup(
            passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passLayout.createSequentialGroup()
                .addGroup(passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(dateValidite, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(passLayout.createSequentialGroup()
                        .addGroup(passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(passLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(NumCin1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(passLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(couleur, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(passLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numPass, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateDeliv, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        passLayout.setVerticalGroup(
            passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCin1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateDeliv))
                .addGap(47, 47, 47)
                .addGroup(passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(couleur))
                .addGap(65, 65, 65)
                .addGroup(passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateValidite))
                .addGap(135, 135, 135))
        );

        jLabel11.setText("numPasseport");

        numPasseport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPasseportActionPerformed(evt);
            }
        });

        Trouver.setText("Trouver");
        Trouver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrouverActionPerformed(evt);
            }
        });

        Imprimer.setText("Imprimer");
        Imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimerActionPerformed(evt);
            }
        });

        Back.setText("Back");

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Statistique.setText("voir les statistiques");
        Statistique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatistiqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel11)
                        .addGap(32, 32, 32)
                        .addComponent(numPasseport, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Trouver)
                        .addGap(56, 56, 56))))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(Imprimer)
                .addGap(78, 78, 78)
                .addComponent(Statistique)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(18, 18, 18)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(numPasseport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(Trouver)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Imprimer)
                    .addComponent(Back)
                    .addComponent(Home)
                    .addComponent(Statistique))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimerActionPerformed
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" Carte d'identité nationale");
        pj.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                EN.paint(g2);
                return Printable.PAGE_EXISTS;
            }
        });
        if (pj.printDialog() == false) {
            return;
        }

        try {
            pj.print();
        } catch (PrinterException ex) {

        }
    }//GEN-LAST:event_ImprimerActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Acceuil add = new Acceuil();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void TrouverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrouverActionPerformed
        PasseportDao passeportDao = new PasseportDao();
        Passeport passeport= passeportDao.getBynumCinUtilisateur(Integer.parseInt(numPasseport.getText()));
        
           
        dateDeliv.setText(passeport.getDateDelivrance().toString());
         dateValidite.setText(passeport.getDateValidite().toString());
         couleur.setText(passeport.getCouleurYeux());
         numPasseport.setText("numéro permis: "+passeport.getNumPasseport());
       // numPermis1.setText(String.valueOf(passeport.getNumCinUtilisateur()));
         }//GEN-LAST:event_TrouverActionPerformed

    private void numPasseportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPasseportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPasseportActionPerformed

    private void StatistiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatistiqueActionPerformed
        chartCouleur ch = new chartCouleur();
        ch.setVisible(true);
    }//GEN-LAST:event_StatistiqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showPasseport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showPasseport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showPasseport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showPasseport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showPasseport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Date_validite_permis;
    private javax.swing.JPanel EN;
    private javax.swing.JButton Home;
    private javax.swing.JButton Imprimer;
    private javax.swing.JLabel NumCin;
    private javax.swing.JLabel NumCin1;
    private javax.swing.JButton Statistique;
    private javax.swing.JButton Trouver;
    private javax.swing.JLabel categorie_permis;
    private javax.swing.JLabel couleur;
    private javax.swing.JLabel dateDeliv;
    private javax.swing.JLabel dateValidite;
    private javax.swing.JLabel date_creation_permis;
    private javax.swing.JLabel j;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel numPass;
    private javax.swing.JTextField numPasseport;
    private javax.swing.JLabel numPermis1;
    private javax.swing.JPanel pass;
    // End of variables declaration//GEN-END:variables
}
