services:
    redirect.after.login:
        class: MyApp\UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router]
#    my_app_user.example:
#        class: MyApp\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    setNewPermis:
        class: MyApp\UserBundle\Services\GetPermis
        arguments: [@service_container]